### ISSUE TITLE
build error with folder src/assets

### ISSUE THREAD

**Issue by VHQDevFS** [Phonng/sample-multi-widget-test-typescript-vite#12]
When i add files image or svg in folder src/assets

build folder(dist) has only javascript files and  does not include the files in the assets folder

**Comment by Phonng** [comment]
[VHQDevFS](https://github.com/VHQDevFS) Because the config is for building multi-lib so Vite will not generate folder assets. You can comment the config for lib like the image below and it will work.
<img width="571" alt="image" src="https://github.com/Phonng/sample-multi-widget-test-typescript-vite/assets/28642022/bb6032e8-902d-4829-b8e3-93dabb827055">

**Comment by Phonng** [comment]
[VHQDevFS](https://github.com/VHQDevFS) I do not recommend add files image or svg to src/assets. I know it makes it easier to reference them from your code and they will be automatically included in the build process. But the build process will be slower and the files will be bigger
